### PR TITLE
Stories/dt/paragraphcount #34

### LINKED ISSUE #34: update for paragraph count

### PR DESCRIPTION
**Pull request by terw-dan**
fixes #34 
Now checks on double linebreaks if there are no paragraphs.

### CODE REVIEW

**Comment by andizer** [comment]
CR done

**Comment by Petervw** [comment]
The keyword was not placed in the first paragraph. The analysis says it is.

image

**Comment by Petervw** [comment]
The link to Flesch–Kincaid readability tests does not open in a new window, please open the link on a new tab/window.

**Comment by Petervw** [comment]
When I use spaces around the focus keyword, the string is not being trimmed. Is that expected behaviour? I use a focus keyword like: " snippet ", which gives me a different result than "snippet".

**Comment by Petervw** [comment]
A few more things to consider:
 - When I enter the focus keyword "SOLID" and use it in the page title as "Solid", was the focus keyword not found;
 - Adding "> in a small text, the Flesch reading ease is recalculated with a higher score;

**Comment by Petervw** [comment]
When I enter a very long meta description, the output in the snippet preview is not limited. The meta description needs to be limited to 156 chars.

**Comment by terw-dan** [comment]
Fixes for all issues are in #42

**Pull request closed without merging**
